# Generated by Django 5.2.6 on 2025-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_portfoliomodel_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('description', models.TextField(verbose_name='Qisqacha tavsif')),
                ('skills', models.TextField(verbose_name='Ko‘nikmalar (vergul bilan ajrating)')),
                ('experience', models.TextField(verbose_name='Ish tajribasi')),
                ('education', models.TextField(verbose_name='Ta’lim')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Rezume',
                'verbose_name_plural': 'Rezume',
            },
        ),
    ]
